### ISSUE TITLE
QueryParam not working following a static path

### ISSUE THREAD

**Issue by thomassun** [ollls/zio-tls-http#24]
with this case   ` case GET -> Root / "user" :? uid(parm) =>`
where uid is defined as `object uid extends QueryParam("uid")`
I expect request like /user?uid=1234 would match the case, but it finally return a 404
it's zio-tls-http 1.1.0-m1 I've used

**Comment by ollls** [comment]
Quick fix applied, but this is rather a placeholder to mark a problem area, it needs to be evaluated, generally speaking we need to apply it only to the last path segment.

**Comment by ollls** [comment]
huge thank you for reporting it!!!!

**Comment by ollls** [comment]
Resubmitted with pattern matching for "/"

**Comment by thomassun** [comment]
Thanks for the quick fix and appreciate you for creating such an awesome project.

**Comment by ollls** [comment]
Fix submitted to 1.1.0-m3
